### ISSUE TITLE
tag and release number did not match

### ISSUE THREAD

**Issue by hubutui** [fengsxy/gpt_batch#2]
tag [1.1.16](https://github.com/fengsxy/gpt_batch/releases/tag/1.1.16) vs 0.1.16. It would be better to make them the same. also, `first` is not a good tag. https://github.com/fengsxy/gpt_batch/archive/refs/tags/fisrt.tar.gz

**Comment by fengsxy** [comment]
Thanks, I would fix it

**Comment by fengsxy** [comment]
Fix it.
