### ISSUE TITLE
partial有什么作用

### ISSUE THREAD

**Issue by wxhheian** [fengsxy/gpt_batch#3]
请教个问题
在处理 process_embedding()方法的时候
fixed_get_embedding = partial(self.get_embedding)

但是在处理 process_attitude()的时候没有类似这样的操作
fixed_get_attitude = partial(self.get_attitude)

我试了下两个都可以跑通。不知道作者有什么考量吗

**Comment by fengsxy** [comment]
partial是用来固定参数的，在函数式编程传参希望只传一个参数，所以使用partial, 这个代码是第一版中遗留的问题，后面把所有的传参方法都放入类方法中self.xx来共享上下文了，后续可以考虑美化下代码。
